Authentication/Authentication/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Login_app.urls'))
]

Authentication/Login_app/urls.py
import imp
from xml.dom.minidom import Document
from django.urls import path
from django.conf import settings
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns
from . import views
app_name = 'Login_app'
urlpatterns = [
    path('', views.Index, name='index'),
    path('registration/', views.Registration, name='registration'),
    path('login/', views.Login_page, name='login'),
    path('user_login/', views.user_login, name='user_login'),
    path('logout/', views.user_logout, name='logout'),


]
#for image
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Authentication/Login_app/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class UserInfo(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE,)
    facebook_id = models.URLField(blank=True)
    profile_pic = models.ImageField(upload_to = 'profile_pics', blank=True)

    def __str__(self):
        return self.user.username
    

Authentication/Login_app/views.py
from django.shortcuts import render
from django.contrib.auth.models import User
from Login_app.models import UserInfo
from django.urls import reverse
from django.http import HttpResponseRedirect, HttpResponse
from  django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required



from Login_app.registration import UserInfoForm, UserForm

# Create your views here.

def Index(request):
    diction = {}
    if request.user.is_authenticated:
        current_user = request.user
        user_id = current_user.id
        user_basic_info = User.objects.get(pk = user_id)
        user_more_info = UserInfo.objects.get(user__pk = user_id)
        diction = {
            'user_basic_info' : user_basic_info,
            'user_more_info' : user_more_info
        }
    return render(request, 'Login_app/index.html', context=diction)

def Registration(request):
    register = False
    if request.method == "POST":
        user_form = UserForm(data=request.POST)
        user_info_form = UserInfoForm(data=request.POST)
        if user_form.is_valid() and user_info_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            userinfo = user_info_form.save(commit=False)
            userinfo.user = user

            if 'profile_pic' in request.FILES:
                userinfo.profile_pic = request.FILES['profile_pic']
            
            userinfo.save()
            register = True
    else:
        user_form = UserForm()
        user_info_form = UserInfoForm()
    diction = {'userinfo': user_form, 'usermoreinfo': user_info_form, 'registration': register}
    return render(request, 'Login_app/registration_form.html', context=diction)


def Login_page(request):
    return render(request, 'Login_app/login_form.html', context={})

def user_login(request):
    if request.method == "POST":
        user_name = request.POST.get('username')
        user_password = request.POST.get('password')
        print(user_name)
        print(user_password)
        user = authenticate(username = user_name, password = user_password)
        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('Login_app:index'))
            else:
                return HttpResponse("User not active")
        else:
            return HttpResponse("Invalid username and password")
    else:
        return HttpResponseRedirect(reverse('Login_app:login')) 

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('Login_app:login'))

Authentication/templates/Login_app/index.html
{% extends 'base.html' %}
{%block body_block %}
<h1>Index Page</h1>

{% if user.is_authenticated %}
<h1>You are logged-in</h1>
<h3>Hi! {{user_basic_info.username}}</h3>
<h3>Your email : {{user_basic_info.email}}</h3>
<h3>Facebook Id : <a href="{{user_more_info.facebook_id}}">{{user_more_info.facebook_id}}</a> </h3>
<img src="media/{{user_more_info.profile_pic}}" alt="" width="250px">

{% else %}
<h1>Please Login</h1>
{% endif %}
{% endblock %}

Authentication/templates/Login_app/login_form.html
{% extends 'base.html' %}
{%block body_block %}

<form action="{% url 'Login_app:user_login' %}" method="POST">
    <fieldset>
        <legend>Login</legend>
        <label class="form-label" for="username">Username</label>
        <input class="form-control" type="text" name="username">

        <label class="form-label" for="Password">Password</label>
        <input class="form-control" type="password" name="password">
        <br>
        <input class="btn btn-primary" type="submit" value="Login" name="submit">
    </fieldset>
    {% csrf_token %}
</form>

{% endblock %}

Authentication/templates/Login_app/registration_form.html
{% extends 'base.html' %}
{%block body_block %}
<h1>Registration</h1>
{% if registration %}
<div class="alert alert-primary">Registration Successful</div>
{% else %}
<form action="" enctype="multipart/form-data" method="POST">
    {{ userinfo.as_p }}
    {{ usermoreinfo.as_p }}
    {% csrf_token %}
    <input class="btn btn-primary" type="submit" name="submit", value="Registrstion">
</form>
{% endif %}

{% endblock %}

Authentication/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
    <title>Authentication</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
          <a class="navbar-brand" href="#">Authentication</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'Login_app:index' %}">Home</a>
              </li>
              {% if user.is_authenticated %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'Login_app:logout' %}">Logout</a>
              </li>
              {% else %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'Login_app:registration' %}">Regiatration</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'Login_app:login' %}">Login</a>
              </li>
              {% endif %}
             
            </ul>
            <form class="d-flex">
              <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
              <button class="btn btn-outline-success" type="submit">Search</button>
            </form>
          </div>
        </div>
      </nav>
      <div class="container">
      {% block body_block %}

      {% endblock %}

    </div>

    
    
</body>
</html>